# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareUser.ShareUser'),
        ),
        migrations.AlterField(
            model_name='shareditem',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareUser.ShareUser'),
        ),
        migrations.AlterField(
            model_name='space',
            name='added_users',
            field=models.ManyToManyField(to='ShareUser.ShareUser'),
        ),
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces_space_related', to='ShareUser.ShareUser'),
        ),
    ]
