# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
