# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0002_auto_20170224_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
