# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0002_auto_20170222_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='url',
            field=models.CharField(default='localhost', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shareditem',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
