# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareuser',
            name='icon',
            field=models.ImageField(default='user_icons/user_icon.jpg', upload_to='user_icons/'),
        ),
    ]
